name: publish-packages
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: pkgforge-debian
    container:
      image: pkgforge-runner:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build, sign, publish to registry
        uses: https://codeberg.org/regolith-desktop/forgejo-pkgforge-action@v1
        env:
          PKGFORGE_REGISTRY_TOKEN: ${{ secrets.PKGFORGE_REGISTRY_TOKEN }}
